[phases.setup]
nixPkgs = ["nodejs_20", "chromium"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run clean",
  "npm run build -w @crm/web",
  "node tools/copy-web-dist.mjs",
  "npm run prisma:generate -w @crm/backend",
  "npm run build -w @crm/backend"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"




